swagger: '2.0'
info:
  version: '1.0'
  title: "Just Test"
basePath: /
paths:
  /notifications:
    x-summary: Notifications Collection
    get:
      summary: List All Notifications
      responses:
        200:
          description: 200 OK
          examples:
            application/json:
              {
                "data": [
                  {
                    "type": "add-to-favorites-notifications",
                    "id": "f5bc69f2-e742-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-13T16:04:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "6a14272a-e745-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  },
                  {
                    "type": "add-to-favorites-notifications",
                    "id": "a57a4a06-e745-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-13T16:03:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "70fd0368-e745-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  },
                  {
                    "type": "absent-notifications",
                    "id": "ab08d88e-e745-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-12T16:04:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "c21acf32-e745-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  },
                  {
                    "type": "update-characteristics-notifications",
                    "id": "6767ff1e-e746-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-11T12:04:38.213172"
                    }
                  },
                  {
                    "type": "absent-notifications",
                    "id": "bc410b5c-e746-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-11T13:43:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "d86e6220-e746-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  },
                  {
                    "type": "career-confirmed-notifications",
                    "id": "9af64ad8-e747-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-10T02:04:38.213172"
                    }
                  },
                  {
                    "type": "add-to-contacts-notifications",
                    "id": "ff6ae078-e747-11e8-b120-720004bdf8e",
                    "attributes": {
                      "when": "2017-03-09T13:43:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "70fd0368-e745-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  },
                  {
                    "type": "improve-perfomance-notifications",
                    "id": "07143788-e749-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "peopleViewedCount": 378,
                      "when": "2017-03-08T02:04:38.213172"
                    }
                  },
                  {
                    "type": "add-to-contacts-notifications",
                    "id": "ca4c3c9a-e74a-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "when": "2017-03-03T11:43:38.213172"
                    },
                    "relationships": {
                      "subject": {
                        "data": {
                          "type": "people",
                          "id": "1cb37610-e74b-11e8-b120-720004bdf8e0"
                        }
                      }
                    }
                  }
                ],
                "included": [
                  {
                    "type": "people",
                    "id": "6a14272a-e745-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "firstName": "Hester",
                      "lastName": "Fletcher",
                      "avatarUrl": "https://api.adorable.io/avatars/285/hester-fletcher.png"
                    }
                  },
                  {
                    "type": "people",
                    "id": "70fd0368-e745-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "firstName": "Alexander",
                      "lastName": "Foster",
                      "avatarUrl": "https://api.adorable.io/avatars/285/alexander-foster.png"
                    }
                  },
                  {
                    "type": "people",
                    "id": "c21acf32-e745-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "firstName": "Carrie",
                      "lastName": "Flores",
                      "avatarUrl": "https://api.adorable.io/avatars/285/carrie-flores.png"
                    }
                  },
                  {
                    "type": "people",
                    "id": "d86e6220-e746-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "firstName": "Mathilda",
                      "lastName": "Carson",
                      "avatarUrl": "https://api.adorable.io/avatars/285/mathilda-carson.png"
                    }
                  },
                  {
                    "type": "people",
                    "id": "1cb37610-e74b-11e8-b120-720004bdf8e0",
                    "attributes": {
                      "firstName": "Adam",
                      "lastName": "Farmer",
                      "avatarUrl": "https://api.adorable.io/avatars/285/adam-farmer.png"
                    }
                  }
                ]
              }